export const APP_CONSTANTS = {
  KEY_CONFIGURATION_LOGIN: 'getConfigurationLogin',
  KEY_CONFIGURATION: 'getConfiguration',
  KEY_SECTION_HEIGHT: 'getSectionHeight',
  KEY_SECTION_WIDTH: 'getSectionWidth',
  KEY_APP_MAP: 'applicationStore/getAppmap',
  KEY_APP_MAP_COUNTER: 'applicationStore/getAppmapCounter',
  KEY_APP_MAP_TX_ID: 'applicationStore/getAppmapTxId',
  KEY_APP_MAP_PROJECT: 'applicationStore/getAppmapProject',
  KEY_APP_MAP_CONTRACT_ID: 'applicationStore/getAppmapContractId',
  KEY_ASSET: 'searchStore/getAsset',
  KEY_SEARCH_RESULTS: 'searchStore/getSearchResults',
  KEY_PROJECTS: 'searchStore/getProjects',
  KEY_MY_PROJECT: 'projectStore/getProject',
  KEY_MY_PROJECTS: 'projectStore/getProjects',
  KEY_PROFILE: 'authStore/getMyProfile',
  KEY_EVENT_CODE: 'getEventCode',
  SET_EVENT_CODE: 'setEventCode',
  DISP_SAVE_PROJECT: 'projectStore/saveProject',
  KEY_MACS_WALLET: 'stacksStore/getMacsWallet',
  KEY_CONTRACT_DATA: 'stacksStore/getContractData'
}
